### ISSUE TITLE
errojs

### ISSUE THREAD

**Issue by Hoshino2123** [Pedro-Magalhaes-Coding/PAP_PedroMagalhaes#1]
então, quando eu clico no botão de criar conta aparece esse erro e eu não sei porque:
![image](https://user-images.githubusercontent.com/65288010/170881930-2bb81fd2-f197-4ec2-90e9-d371c402042b.png)
![image](https://user-images.githubusercontent.com/65288010/170881995-75cc5e60-d67e-4e93-9689-a6e49a1f96f4.png)
![image](https://user-images.githubusercontent.com/65288010/170882059-8b321eb9-eb0e-4535-8b73-f44f1445a333.png)

**Comment by miltonbolonha** [comment]
O código está diferente da imagem.
Falta informação de ambiente para que eu possa também rodar o mesmo ambiente que você.
Eu preciso ser capaz de reproduzir o erro para poder ajudar.

Acredito que esse listener do DOM pode estar causando o conflito.
Eu testei o código isolando o HTML e JS. Não tive problemas e o js foi corretamente,

Você ainda está com o mesmo problema? @Pedro-Magalhaes-Coding

**Comment by Hoshino2123** [comment]
Já resolvi o erro, era porque estava a puxar o ficheiro com nome antigo,
mas obrigado na mesma pela ajuda.

miltonbolonha ***@***.***> escreveu no dia domingo,
29/05/2022 à(s) 21:15:

**Comment by miltonbolonha** [comment]
@Pedro-Magalhaes-Coding ,  parabéns. Não duvide do método de organizar. Você é antes um curador de códigos e um escritor, depois um programador. Por isso, os processos da profissão são tão importantes.

Não deixe de estar em um grupo mais fechado e com mentores/professores, existem muitos por aí. Nunca pague muito, de preferência gratuito. E sempre mande a issue.

Agora você precisa fechar essa issue.

**Comment by Hoshino2123** [comment]
Obrigado

A terça, 31/05/2022, 14:14, miltonbolonha ***@***.***>
escreveu:
